import React from "react";
import '@/app/globals.css';
import AuthProvider from "@/context/AuthProvider";
import type {Metadata} from 'next'
import Script from "next/script";
import TopNavbar from "@/components/Navbar";
import { Gothic_A1 } from "next/font/google";

const gothic = Gothic_A1({
    weight: '500',
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <head>
            <title>AU App</title>
        </head>
        <Script src="https://cdn.iamport.kr/v1/iamport.js"/>
        <body  className={`${gothic.className} mx-auto`}>
        <AuthProvider>
            {children}
        </AuthProvider>
        </body>
        </html>
    )
}