import React from "react";
import '@/app/globals.css';
import {Inter} from 'next/font/google'
import AuthProvider from "@/app/context/AuthProvider";
import type {Metadata} from 'next'
import Script from "next/script";
import TopNavbar from "@/components/Nav/Navbar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <head>
            <title>AU App</title>
        </head>
        <Script src="https://cdn.iamport.kr/v1/iamport.js"/>
        <body>
        <AuthProvider>
            <div>
                <TopNavbar/>
                <h2 className='text-2xl font-bold'>임시 페이지</h2>
            </div>
            {children}
        </AuthProvider>
        </body>
        </html>
    )
}